// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'buttonWithMargin': string;
  'forceMobileLayout': string;
  'gameDeskFooter': string;
  'innerContainer': string;
  'outerContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
