// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cell': string;
  'content': string;
  'gameBoardCell': string;
  'icon': string;
  'matrix': string;
  'row': string;
  'symbol': string;
}
export const cssExports: CssExports;
export default cssExports;
