// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'block': string;
  'cell': string;
  'row': string;
  'separator': string;
}
export const cssExports: CssExports;
export default cssExports;
