// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'difficulty': string;
  'forceMobileLayout': string;
  'header': string;
  'leftSide': string;
  'rightSide': string;
  'settings': string;
  'sideContent': string;
  'time': string;
  'timer': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
