// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'boardPreview': string;
  'keyboard': string;
  'matrix': string;
  'matrixContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
