// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bottomContentOffset': string;
  'bottomToolbar': string;
  'container': string;
  'content': string;
  'forceMobileLayout': string;
  'gameDesk': string;
  'toolbar': string;
  'topContentOffset': string;
}
export const cssExports: CssExports;
export default cssExports;
