// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'key': string;
  'keyboard': string;
  'keyboardContent': string;
  'separator': string;
}
export const cssExports: CssExports;
export default cssExports;
