// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'icon': string;
  'input': string;
  'mode': string;
  'modeUI': string;
  'separator': string;
  'switch': string;
}
export const cssExports: CssExports;
export default cssExports;
