// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'selected': string;
  'value': string;
  'valuePicker': string;
}
export const cssExports: CssExports;
export default cssExports;
