// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'back': string;
  'buttonWrapper': string;
  'close': string;
  'content': string;
  'contentWrapper': string;
  'drawer': string;
  'header': string;
  'isNested': string;
  'primaryAction': string;
  'title': string;
  'ui': string;
}
export const cssExports: CssExports;
export default cssExports;
