// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttonWrapper': string;
  'header': string;
  'ios': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
