// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'handle': string;
  'input': string;
  'switch': string;
  'ui': string;
}
export const cssExports: CssExports;
export default cssExports;
