// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'tab': string;
  'tabInput': string;
  'tabSwitcher': string;
  'tabUi': string;
}
export const cssExports: CssExports;
export default cssExports;
