// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'app': string;
  'main': string;
  'phoneHeader': string;
}
export const cssExports: CssExports;
export default cssExports;
