// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'congratulations': string;
  'illustration': string;
  'text': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
