enum Dialog {
  CONGRATULATIONS = 'Dialog.CONGRATULATIONS',
  GAMEPLAY_GUIDE = 'Dialog.GAMEPLAY_GUIDE',
  NEW_GAME = 'Dialog.NEW_GAME',
  PAUSE = 'Dialog.PAUSE',
  SETTINGS = 'Dialog.SETTINGS',
  THEME_CHOOSER = 'Dialog.THEME_CHOOSER',
  THEME_PREVIEW = 'Dialog.THEME_PREVIEW',
}

export default Dialog
