// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttons': string;
  'illustration': string;
  'pause': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
