// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'arrow': string;
  'item': string;
  'switch': string;
}
export const cssExports: CssExports;
export default cssExports;
