// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'chooser': string;
  'option': string;
  'optionRow': string;
}
export const cssExports: CssExports;
export default cssExports;
