// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'background': string;
  'board': string;
  'boardContainer': string;
  'bottomSpace': string;
  'preview': string;
}
export const cssExports: CssExports;
export default cssExports;
