// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cell': string;
  'horizontalSeparator': string;
  'matrix': string;
  'verticalSeparator': string;
}
export const cssExports: CssExports;
export default cssExports;
